{{- if and .Values.superset.bigquery.enabled (not .Values.superset.bigquery.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "superset.fullname" . }}-bigquery-sa
  namespace: {{ include "superset.namespace" . }}
  labels:
    {{- include "superset.labels" . | nindent 4 }}
type: Opaque
data:
  service-account.json: {{ .Values.superset.bigquery.serviceAccountJson | b64enc | quote }}
{{- end }}
